# -*- coding: utf-8 -*-
"""Proyek Analisis Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ug4Ox4qIFDSo1koFA0XiNJE-ce12rECy

# Proyek Analisis Data: [Bike Sharing Dataset]
- **Nama:** [Input Nama]
- **Email:** [Input Email]
- **ID Dicoding:** [Input Username]

## Menentukan Pertanyaan Bisnis

- Pertanyaan 1: Apa faktor utama yang mempengaruhi jumlah penyewaan sepeda harian?

- Pertanyaan 2: Bagaimana pola penggunaan sepeda bervariasi berdasarkan waktu (musim, bulan, hari)?

## Import Semua Packages/Library yang Digunakan
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

"""## Data Wrangling

### Gathering Data
"""

from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv('day.csv')
df.head()

"""**Insight:**
- Dataset terdiri dari beberapa fitur seperti hari, musim, suhu, kelembaban, dan jumlah sepeda yang disewa per hari.

- Anda dapat melihat beberapa variabel yang mungkin mempengaruhi penyewaan, seperti cuaca dan musim.

### Assessing Data
"""

# Check for missing data
df.info()

# Check for outliers
df.describe()

"""**Insight:**
- Tidak ada missing values pada dataset.

- Beberapa fitur numerik seperti 'temp' (suhu) dan 'cnt' (jumlah sepeda) mungkin perlu divisualisasikan lebih lanjut untuk melihat distribusi data.

### Cleaning Data
"""

# Optional cleaning steps (if needed)
df['season'] = df['season'].astype('category')

"""**Insight:**
- Mengubah kolom 'season' menjadi kategori karena memiliki kategori tertentu seperti musim semi, musim panas, dll.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

# Visualize bike rentals per season
sns.boxplot(x='season', y='cnt', data=df)
plt.title('Bike Rentals by Season')
plt.show()

"""**Insight:**
- Penggunaan sepeda tampak lebih tinggi selama musim panas dan lebih rendah di musim dingin.

## Visualization & Explanatory Analysis

### Pertanyaan 1: Faktor yang Mempengaruhi Penyewaan Sepeda
"""

# Menghitung korelasi
correlation = df[['atemp', 'hum', 'windspeed', 'cnt']].corr()

# Visualisasi korelasi
plt.figure(figsize=(8,6))
sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.title('Korelasi antara Variabel Cuaca dan Penyewaan Sepeda')
plt.show()

"""### Pertanyaan 2:"""

# Visualisasi tren penggunaan sepeda sepanjang waktu
df['mnth'] = pd.to_datetime(df['dteday']).dt.month

plt.figure(figsize=(10,6))
sns.lineplot(x='mnth', y='cnt', data=df)
plt.title('Tren Penyewaan Sepeda per Bulan')
plt.xlabel('Bulan')
plt.ylabel('Jumlah Penyewaan')
plt.show()

"""**Insight:**
- Suhu dan musim adalah faktor yang paling mempengaruhi penyewaan sepeda.

- Penggunaan sepeda cenderung meningkat selama bulan-bulan musim panas dan menurun di musim dingin.

## Analisis Lanjutan (Opsional)
"""



"""## Conclusion

- Conclution pertanyaan 1: Faktor cuaca seperti suhu dan musim memiliki pengaruh besar terhadap penyewaan sepeda.

- Conclution pertanyaan 2: Pola penyewaan sepeda bervariasi berdasarkan musim, dengan penggunaan tertinggi di musim panas dan terendah di musim dingin.
"""

# Streamlit app code
st.title('Bike Sharing Analysis')
st.write('Analisis berdasarkan faktor-faktor yang mempengaruhi penyewaan sepeda.')

st.subheader('Rentals by Season')
season_fig = sns.boxplot(x='season', y='cnt', data=df)
st.pyplot(season_fig.figure)

st.subheader('Monthly Bike Rentals')
month_fig = sns.lineplot(x='month', y='cnt', data=df)
st.pyplot(month_fig.figure)

# Correlation matrix visualization
st.subheader('Correlation Matrix')
corr_fig = sns.heatmap(corr_matrix, annot=True, cmap='coolwarm')
st.pyplot(corr_fig.figure)
