# -*- coding: utf-8 -*-
"""Proyek Analisis Data 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/114hVypkeYGKMJ2sr-JUpdDZf1bwaLzDp
"""

# Display project information
from IPython.display import display, Markdown

display(Markdown("<h1 style='text-align: center; color: #4CAF50;'>🚴 Proyek Analisis Data: Bike Sharing Dataset</h1>"))
display(Markdown("**Nama:** Jenny Rahma Hidaya"))
display(Markdown("**Email:** m191b4kx2057@bangkit.academy"))
display(Markdown("**ID Dicoding:** jennyrhmaa"))
display(Markdown("---"))

"""## Menentukan Pertanyaan Bisnis

- Pertanyaan 1 : Apa faktor utama yang mempengaruhi jumlah penyewaan sepeda harian?
- Pertanyaan 2 : Bagaimana pola penggunaan sepeda bervariasi berdasarkan waktu (musim, bulan, hari)?

## Import Semua Packages/Library yang Digunakan
"""

!pip install streamlit

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import streamlit as st

"""## Data Wrangling

### Gathering Data
"""

from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv('day.csv')

# Display dataset with improved visuals
display(Markdown("### 📊 Dataset"))
print(df.head())

"""**Insight:**
- Dataset terdiri dari beberapa fitur seperti hari, musim, suhu, kelembaban, dan jumlah sepeda yang disewa per hari.

- Anda dapat melihat beberapa variabel yang mungkin mempengaruhi penyewaan, seperti cuaca dan musim.

### Assessing Data
"""

# Display the first 5 rows of the dataset
display(Markdown("### 📋 5 Baris Pertama dari Dataset:"))
print(df.head())

if df.isnull().sum().sum() == 0:
    print("✅ Tidak ada missing values pada dataset.")
else:
    print("❌ Ada missing values pada dataset.")

# Check for outliers
display(Markdown("### 📈 Statistik Deskriptif:"))
print(df.describe())

"""**Insight:**
- Tidak ada missing values pada dataset.

- Beberapa fitur numerik seperti 'temp' (suhu) dan 'cnt' (jumlah sepeda) mungkin perlu divisualisasikan lebih lanjut untuk melihat distribusi data.

### Cleaning Data
"""

df['season'] = df['season'].astype('category')

"""**Insight:**
- Mengubah kolom 'season' menjadi kategori karena memiliki kategori tertentu seperti musim semi, musim panas, dll.

## Exploratory Data Analysis (EDA)

### Explore ...
"""

display(Markdown("## 🔍 Analisis Penyewaan Sepeda"))
display(Markdown("### 📊 Penyewaan Sepeda per Musim"))

# Plot Bike Rentals by Season
plt.figure(figsize=(10, 6))
sns.boxplot(x='season', y='cnt', data=df, palette="Set2")  # Added color palette
plt.title('Penyewaan Sepeda Berdasarkan Musim', fontsize=16)
plt.ylabel('Jumlah Penyewaan', fontsize=12)
plt.xlabel('Musim', fontsize=12)
plt.show()

"""**Insight:**
Penggunaan sepeda tampak lebih tinggi selama musim panas dan lebih rendah di musim dingin.

## Visualization & Explanatory Analysis

### Pertanyaan 1:
"""

# Correlation Analysis
display(Markdown("### 📊 Analisis Korelasi"))
correlation = df[['atemp', 'hum', 'windspeed', 'cnt']].corr()
plt.figure(figsize=(8, 6))
sns.heatmap(correlation, annot=True, cmap='YlGnBu', fmt=".2f")  # Changed color palette
plt.title('Korelasi antara Variabel Cuaca dan Penyewaan Sepeda', fontsize=16)
plt.show()

"""### Pertanyaan 2:"""

# Monthly bike rentals
df['mnth'] = pd.to_datetime(df['dteday']).dt.month
display(Markdown("### 📅 Tren Penyewaan Sepeda per Bulan"))
plt.figure(figsize=(10, 6))
sns.lineplot(x='mnth', y='cnt', data=df, marker='o', color='orange')  # Added markers and color
plt.title('Tren Penyewaan Sepeda per Bulan', fontsize=16)
plt.xlabel('Bulan', fontsize=12)
plt.ylabel('Jumlah Penyewaan', fontsize=12)
plt.show()

"""**Insight:**
- Pertanyaan 1: Suhu dan musim adalah faktor yang paling mempengaruhi penyewaan sepeda.

- Pertanyaan 2: Penggunaan sepeda cenderung meningkat selama bulan-bulan musim panas dan menurun di musim dingin.

## Analisis Lanjutan (Opsional)

# RFM Analysis
"""

# Menghitung Recency, Frequency, Monetary

# Menghitung Recency (dari tanggal terbaru dalam dataset)
current_date = pd.to_datetime(df['dteday'].max())  # Menggunakan tanggal terakhir dalam dataset
df['dteday'] = pd.to_datetime(df['dteday'])
df['Recency'] = (current_date - df['dteday']).dt.days

# Menghitung Frequency (berdasarkan jumlah hari)
df['Frequency'] = 1  # Karena data per hari, setiap hari dihitung sebagai satu penyewaan

# Menghitung Monetary (menggunakan jumlah penyewaan per hari)
df['Monetary'] = df['cnt']  # Jumlah penyewaan per hari

# Menggabungkan nilai RFM
rfm_df = df[['dteday', 'Recency', 'Frequency', 'Monetary']]

# Menampilkan hasil RFM
print("### RFM Analysis")
print(rfm_df.head())

"""**Insight**: Jumlah penyewaan harian sangat bervariasi, tetapi puncaknya terjadi selama bulan-bulan hangat, seperti Juni hingga Agustus. Ini menunjukkan bahwa permintaan sepeda lebih tinggi selama musim panas, yang mungkin mengindikasikan peluang bisnis yang lebih besar di masa ini.

# Geoanalysis
"""

# Geoanalysis dengan 'season'

plt.figure(figsize=(10, 6))
sns.scatterplot(x='season', y='cnt', size='cnt', sizes=(20, 200), data=df, alpha=0.6, palette='coolwarm')
plt.title('Penyewaan Sepeda Berdasarkan Musim', fontsize=16)
plt.xlabel('Musim', fontsize=12)
plt.ylabel('Jumlah Penyewaan', fontsize=12)
plt.show()

"""**Insight**: Penyewaan sepeda sangat dipengaruhi oleh musim, dengan tingkat penyewaan yang tertinggi pada musim panas dan terendah pada musim dingin. Ini dapat membantu perencana transportasi atau bisnis penyewaan sepeda untuk memperkirakan stok sepeda dan promosi musiman yang lebih efektif.

# Clustering
"""

# Mengambil dua fitur untuk clustering
data = df[['atemp', 'hum']]

# Menentukan jumlah cluster
num_clusters = 3  # Misalkan kita ingin 3 cluster

# Menghitung centroid secara manual (gunakan rata-rata)
centroids = data.groupby(np.floor(data.index / (len(data) / num_clusters))).mean().reset_index(drop=True)

# Menetapkan cluster ke setiap data
data['Cluster'] = (data.index // (len(data) // num_clusters))

# Visualisasi hasil clustering
plt.figure(figsize=(10, 6))
sns.scatterplot(x='atemp', y='hum', hue='Cluster', data=data, palette='Set1', alpha=0.6)
plt.scatter(centroids['atemp'], centroids['hum'], color='black', marker='X', s=100, label='Centroids')
plt.title('Clustering Penyewaan Sepeda Berdasarkan Suhu dan Kelembapan', fontsize=16)
plt.xlabel('Suhu (atemp)', fontsize=12)
plt.ylabel('Kelembapan (hum)', fontsize=12)
plt.legend()
plt.show()

"""**Insight**: Kondisi cuaca memainkan peran penting dalam memengaruhi pola penyewaan sepeda. Pengguna cenderung lebih aktif pada hari-hari yang lebih cerah, hangat, dan tidak terlalu lembap. Faktor cuaca bisa digunakan sebagai indikator prediksi permintaan penyewaan sepeda.

## Conclusion

- Conclution pertanyaan 1: Conclution pertanyaan 1: Faktor cuaca seperti suhu dan musim memiliki pengaruh besar terhadap penyewaan sepeda.

- Conclution pertanyaan 2: Pola penyewaan sepeda bervariasi berdasarkan musim, dengan penggunaan tertinggi di musim panas dan terendah di musim dingin.
"""

# Add a footer
display(Markdown("---"))
display(Markdown("📊 *Data diambil dari Bike Sharing Dataset*"))